// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 20
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){


var za=this,Aa=function(){var a=YT.Player,b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},Ba=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Ca=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Da=function(a){if(null==a)return String(a);var b=Ca.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Ea=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},ma=function(a){if(!a||"object"!=Da(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Ea(a,"constructor")&&!Ea(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Ea(a,b)},Ga=function(a,b){var c=b||("array"==Da(a)?[]:{}),d;for(d in a)if(Ea(a,d)){var e=a[d];"array"==Da(e)?("array"!=Da(c[d])&&(c[d]=[]),c[d]=Ga(e,c[d])):ma(e)?(ma(c[d])||(c[d]={}),c[d]=Ga(e,c[d])):c[d]=e}return c};var qa=null,Ha=Math.random(),Ia=null,Ja=null,Ka={},La={};var Ma,Na,Oa,Pa,Qa,Ra,Sa,Ua,Va,Wa,Xa,Ya,R,Za,$a,ab,bb,cb,db,eb,fb,gb,hb,ib,jb,kb,mb,ob,pb,qb,rb,sb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Hb,Ib,Kb,Lb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,S,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,ld,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,
be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue;
(function(){var a=function(a){return{toString:function(){return a}}};Ma=a("");Na=a("");Oa="";Pa=a("");Qa=a("");Ra=a("");Sa=a("");Ua=a("");Va=a("");Wa=a("");Xa=a("");Ya=a("0");R=a("1");Za=a("");$a=a("");ab=a("");
bb=a("");cb=a("");db=a("");eb=a("");fb=a("");gb=a("");hb=a("");ib=a("");jb=a("");kb=a("");mb=a("");ob=a("");pb=a("");qb=
a("");rb=a("");sb=a("");tb=a("");ub=a("");vb=a("");wb=a("");xb=a("2");yb=a("");zb=a("");Ab=a("");Bb=a("");Cb=a("");Db=a("");Eb=a("");Fb=a("");Hb=a("");Ib=a("");
Kb=a("");Lb=a("");Mb=a("");Nb=a("");Ob=a("");Pb=a("");Qb=a("");Rb=a("");Sb=a("");Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("");Yb=a("");Zb=a("");$b=a("");
ac=a("");bc=a("");cc=a("");dc=a("");ec=a("");fc=a("");gc=a("");hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");
rc=a("");sc=a("");tc=a("");uc=a("");vc=a("");wc=a("");xc=a("");yc=a("");zc=a("");Ac=a("");Bc=a("3");Cc=a("");Dc=a("10");Ec=a("11");Fc=a("");Gc=a("");Hc=a("4");
S=a("");Ic=a("");Jc=a("");Kc=a("");Lc=a("");Mc=a("5");Nc=a("");Oc=a("");Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=a("");$c=
a("");ad=a("");bd=a("");cd=a("");dd=a("");ed=a("");fd=a("");gd=a("");hd=a("");id=a("");ld=a("");od=a("");pd=a("");qd=a("");rd=a("");sd=a("");td=a("");ud=a("");vd=a("");wd=a("");
xd=a("");yd=a("");zd=a("");Ad=a("");Bd=a("");Cd=a("");Dd=a("");Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");
Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");
fe=a("8");ge=a("");he=a("");ie=a("");je=a("");ke=a("");le=a("");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");
we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De="";Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");Me=a("");
Ne=a("");Oe=a("");Pe=a("9");Qe=a("");Re=a("");Se=a("");Te=a("");Ue=a("")})();var Ve=function(){},L=function(a){return"function"==typeof a},U=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},We=function(a){return"number"==Da(a)&&!isNaN(a)},Xe=function(a){return/^[0-9]+$/.test(a)},Ye=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},Ze=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},M=function(a){return Math.round(Number(a))||0},oa=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},$e=function(a){var b=[];if(U(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},K=function(){return new Date},af=function(a,b){if(!We(a)||!We(b)||a>b)a=0,b=2147483647;return Math.round(Math.random()*(b-a)+a)},bf=function(){this.prefix="gtm.";this.values={}};bf.prototype.set=function(a,b){this.values[this.prefix+a]=b};bf.prototype.get=function(a){return this.values[this.prefix+a]};bf.prototype.contains=function(a){return void 0!==this.get(a)};
var cf=function(a,b,c){try{if(!a[bd])return a[Bc](a,b||Ve,c||Ve);c&&c()}catch(d){}return!1},df=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=Ze(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},ef=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},ff=function(a){return function(){return a("GTM-N7VWVN")}},gf=function(a){for(var b=0;b<a.length;b++)a[b]()},ka=K().getTime(),na=function(a,
b,c){return a&&a.hasOwnProperty(b)?a[b]:c},hf=function(a,b,c){a.prototype["gtm_proxy_"+b]=a.prototype[b];a.prototype[b]=c},jf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},la=function(a,b,c){if(!(b&&c&&jf(a)&&U(a)&&0!=a.length))return null;for(var d={},e=0;e<a.length;e++)a[e]&&a[e].hasOwnProperty(b)&&a[e].hasOwnProperty(c)&&(d[a[e][b]]=a[e][c]);return d},kf=function(a,b){0==b?a.Oa=!0:a.complete=!0;var c=a.g;a.o&&(a.o.Ba[c]=b);Ka[c]&&(Ka[c].state=b)},lf=function(a,b){a.sort(function(a,
d){return b(a,d)?-1:b(d,a)?1:0})};var J=window,P=document,of=navigator,I=function(a,b,c){var d=J[a];J[a]=void 0===d||c?b:d;return J[a]},O=function(a,b,c,d){return(d||"http:"!=J.location.protocol?a:b)+c},vf=function(a){var b=P.getElementsByTagName("script")[0]||P.body||P.head;b.parentNode.insertBefore(a,b)},pa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},p=function(a,b,c){var d=P.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;pa(d,b);c&&(d.onerror=c);vf(d)},ha=function(a,b){var c=P.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";vf(c);pa(c,b);void 0!==a&&(c.src=a);return c},A=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},V=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},r=function(a){J.setTimeout(a,0)},ta=!1,
ua=[],wf=function(a){if(!ta){var b=P.createEventObject,c="complete"==P.readyState,d="interactive"==P.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){ta=!0;for(var e=0;e<ua.length;e++)ua[e]()}ua.push=function(){for(var a=0;a<arguments.length;a++)r(arguments[a]);return 0}}},xf=0,yf=function(){if(!ta&&140>xf){xf++;try{P.documentElement.doScroll("left"),wf()}catch(a){J.setTimeout(yf,50)}}},Af=function(a){var b=P.getElementById(a);if(b&&zf(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(zf(document.all[a][c],
"id")==a)return document.all[a][c];return b},zf=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Bf=function(a){return a.target||a.srcElement||{}},xa=function(a){var b=P.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},Cf=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&
(e=null);return e},Df=!1,Ef=[],Ff=function(){if(!Df){Df=!0;for(var a=0;a<Ef.length;a++)Ef[a]()}},Gf=function(a){a=a||J;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},va=function(a){window.console&&window.console.log&&window.console.log(a)};var Hf=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||J.location.protocol.replace(":","")).toLowerCase();switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||J.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:J.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=Ye(d||[],k[k.length-
1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var m=f.split("&"),l=0;l<m.length;l++){var n=m[l].split("=");if(decodeURIComponent(n[0]).replace(/\+/g," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},If=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},ya=function(a){var b=P.createElement("a");
a&&(b.href=a);return b};var ga=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ba=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=Hf(ya(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};var ea=function(a,b){p("//bat.bing.com/bat.js",a,b)},u=J,da=function(a,b,c){b&&(void 0===u[a]||c&&!u[a])&&(u[a]=b);return u[a]},aa=function(a,b,c){return("https:"==J.location.protocol?a:b)+c};var Jf=new bf,Kf={},Mf={set:function(a,b){Ga(Lf(a,b),Kf)},get:function(a){return C(a,2)},reset:function(){Jf=new bf;Kf={}}},C=function(a,b){if(2==b){for(var c=Kf,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Jf.get(a)},Lf=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Nf=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Of={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Pf={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Qf=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Rf=function(){var a=C("gtm.whitelist");
var b=a&&Qf($e(a),Of),c=C("gtm.blacklist")||C("tagTypeBlacklist")||[];Nf.test(J.location&&J.location.hostname)&&(c=$e(c),c.push("nonGooglePixels","nonGoogleScripts"));var d=c&&Qf($e(c),Pf),e={};return function(f){var g=f&&f[Bc];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>Ye(b,g.a))if(g.b&&0<g.b.length)for(var k=0;k<g.b.length;k++){if(0>Ye(b,
g.b[k])){h=!1;break a}}else{h=!1;break a}h=!0}var m=!1;if(c){var l;if(!(l=0<=Ye(d,g.a)))a:{for(var n=g.b||[],q=new bf,t=0;t<d.length;t++)q.set(d[t],!0);for(t=0;t<n.length;t++)if(q.get(n[t])){l=!0;break a}l=!1}m=l}return e[g.a]=!h||m}};var _c=function(a){return a[Pe]};_c.a="c";_c.b=["google"];var mf=function(a){var b=P;return Sf?b.querySelectorAll(a):null},Tf=!1;if(P.querySelectorAll)try{var Uf=P.querySelectorAll(":root");Uf&&1==Uf.length&&Uf[0]==P.documentElement&&(Tf=!0)}catch(a){}var Sf=Tf;var _eu=function(a){var b=String(C("gtm.elementUrl")||a[Yb]||""),c=ya(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Ja};_e.a="e";_e.b=["google"];var Zf=/(^|\.)doubleclick\.net$/i,$f=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,ag=function(a){for(var b=String(P.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=Ze(e[0]);if(f&&f==a){var g=Ze(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},bg=function(a,b,c,d,e){if(Zf.test(P.location.hostname)||"/"==c&&$f.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=P.cookie;P.cookie=f;return g!=
P.cookie||0<=Ye(ag(a),b)},cg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},dg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},eg=function(){var a=Hf(J.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var fg=function(a,b){this.f=a;this.i=b};fg.prototype.toString=function(){var a=""+this.f;1<this.i&&(a=a+"-"+this.i);return a};var gg=function(a,b){this.za=a;this.ba=b};gg.prototype.toString=function(){return""+this.ba+"."+this.za};var jg=function(a,b){var c=new hg(null,a,b);ig(c);return c},hg=function(a,b,c){this.Ha=Math.floor(K().getTime()/864E5);this.aa=b||"auto";this.T=c||"/";var d=cg(this.aa),e=dg(this.T);this.C=a||new fg(d,e);this.h=[];this.A=new bf},lg=function(a,b,c){b&&(""==c.za?kg(a,b):(a.A.contains(b)||a.h.push(b),a.A.set(b,c)))},mg=function(a,b){for(var c=0;c<b.length;c++)lg(a,b[c][0],b[c][1])},kg=function(a,b){var c=Ye(a.h,b);0<=c&&a.h.splice(c,1);a.A.set(b,void 0)},ng=function(a){for(var b=[],c=0;c<a.h.length;c++){var d=
a.h[c];b.push([d,a.A.get(d)])}return b},og=function(a){for(var b=0,c=0;c<a.h.length;c++)b=Math.max(b,a.A.get(a.h[c]).ba);return 864E5*b};hg.prototype.toString=function(){if(0==this.h.length)return"";for(var a=[],b=0;b<this.h.length;b++){var c=this.h[b];a.push(""+c+"."+this.A.get(c).toString())}return"GAX1."+this.C.toString()+"."+a.join("!")};
var pg=function(a,b){for(var c=new Date,d=dg(a.T),e=[],f=0;f<a.h.length;f++){var g=a.h[f];a.A.get(g).ba<a.Ha&&e.push(g)}for(f=0;f<e.length;f++)kg(a,e[f]);if(a.h.length>(b||10))return!1;c.setTime(og(a));if("auto"!=a.aa)return bg("_gaexp",a.toString(),a.T,a.aa,c);for(var h=eg(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.C=new fg(cg(h[k]),d),bg("_gaexp",a.toString(),a.T,h[k],c)))return!0;return!1},ig=function(a){for(var b=a.C.f,c=a.C.i,d=ag("_gaexp"),e=[],f=0;f<d.length;f++){var g=qg(a,d[f]);g&&e.push(g)}lf(e,
function(a,d){var e=a.C,f=d.C;return e.f==f.f&&e.i==f.i?!1:e.f==b&&e.i==c?!0:f.f==b&&f.i==c?!1:e.f==b?f.f!=b||e.i<f.i:f.f==b?!1:e.i==c?f.f!=b&&(f.i!=c||e.f<f.f):f.i==c?!1:e.f<f.f||e.f==f.f&&e.i<f.i});a.C=0<e.length?e[0].C:new fg(b,c);for(f=e.length-1;0<=f;f--)mg(a,ng(e[f]))},qg=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=Ze(e[0]);if(0!=f.length){var g=2==e.length?Ze(e[1]):"1";if(Xe(f)&&Xe(g)){d=new fg(M(f),M(g));
break a}}}d=void 0}if(d){for(var h=new hg(d,a.aa,a.T),k=(c[2]||"").split("!"),m=0;m<k.length;m++){var l=k[m].split(".");if(3==l.length){if(!Xe(l[1]))return;lg(h,l[0],new gg(l[2],M(l[1])))}}return h}}};var _f=function(a){var b=String(C("gtm.referrer")||P.referrer);if(!b)return b;var c=ya(b);return b};_f.a="f";_f.b=["google"];var ia=function(a){var b=J.location,c;(c=a[Nb]?a[Nb]:C("gtm.url"))&&(b=ya(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[xb]&&(f=Hf(b,a[xb],a[$d],a[Xb],a[Nd]));return f},_u=ia;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[Ya])==String(a[R])};_eq.a="eq";_eq.b=["google"];var Eg=Math.random(),Fg="1.000000">Eg;var Gg=Ve;var Hg=Ve,Ig=[],Jg=!1,Kg=function(a){return J["dataLayer"].push(a)},Lg=function(a){var b=!1;return function(){!b&&L(a)&&r(ff(a));b=!0}},Rg=function(){for(var a=!1;!Jg&&0<Ig.length;){Jg=!0;var b=Ig.shift();if(L(b))try{b.call(Mf)}catch(sa){}else if(U(b))a:{var c=b;if("string"==Da(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Kf,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(sa){}}}else{var k=b,m=void 0;for(m in k)if(k.hasOwnProperty(m)){var l=m,n=
k[m];Jf.set(l,n);Ga(Lf(l,n),Kf)}var q=!1,t=k.event,v=void 0;if(t){v=ka++;Ja=t;if(!k["gtm.uniqueEventId"]){var x=v;Jf.set("gtm.uniqueEventId",x);Ga(Lf("gtm.uniqueEventId",x),Kf)}var z=Lg(k.eventCallback),E=k.eventTimeout;E&&J.setTimeout(z,Number(E));q=Hg(v,t,z,k.eventReporter)}Ia||(Ia=k["gtm.start"])&&Gg();var F=k,D=v,y=t,G=Kf;if(!q){var B=v,H=t;}Ja=null;a=q||a}var Q=b,N=Kf;Qg();Jg=!1}return!a};var Sg,Tg,Ug,Vg=/(Firefox\D28\D)/g.test(of.userAgent),ah=function(a,b){return function(c){c=c||J.event;var d=Bf(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=Cf(d,["a","area"]),e=!d||!d.href||Wg(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?Ug:Tg;if(c.defaultPrevented||!1===c.returnValue||c.oa&&c.oa()){if(d){var g={simulateDefault:!1},h=Xg(f,["wnc","nwnc"]);h&&Yg(a,d,g,f.wt,h)}}else{if(d){var g={},k,m=Xg(f,
["wnc","nwnc","nwc","wc"]);(k=Yg(a,d,g,f.wt,m))||(Zg(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&Vg;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=$g(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},Yg=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||zf(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event=
"gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=bh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=ch(b);g.eventTimeout=f;g.eventCallback=dh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return Kg(g)},
ch=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},eh=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},$g=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(of.userAgent),e=eh(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=J.frames&&J.frames[f]||J[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+K().getTime(),b.targetWindow=J.open("",b.targetWindowName));break;default:d&&!J.frames[e]?(b.simulateDefault=!1,c=!0):(J.frames[e]||(b.targetWindowName=e),b.targetWindow=J.frames[e]||J.open("",e))}return c},bh=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||K().getTime(),500>K().getTime()-c&&J.setTimeout(bh(a,b,c),25)))}},dh=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);P.gtmSubmitFormNow=!0;fh(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||K().getTime(),500>K().getTime()-c&&J.setTimeout(dh(a,b,c),25)}},Xg=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},gh=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},Zg=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<hh.length;c++)if(a.passingRules[c]){var d=hh[c],e=ih[c],f=e&&e[0]&&e[0][0]||e[1]&&e[1][0];if(f&&"0"!=f&&(b.wc[f]||b.wnc[f]))for(var g=d[1],h=0;h<g.length;h++)if(a.resolvedTags[g[h]])return!0}return!1},jh=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(P.gtmHasClickListenerTag)return;P.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=Bf(a);b&&Yg("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Sg&&(Sg=If(P.location));gh(Tg,b||!1,c||!1,d,e);if(P.gtmHasLinkClickListenerTag)return;
P.gtmHasLinkClickListenerTag=!0;f="click";g=ah(a,b||!1);break;case "FORM_SUBMIT":gh(Ug,b||!1,c||!1,d,e);if(P.gtmHasFormSubmitListenerTag)return;P.gtmHasFormSubmitListenerTag=!0;f="submit";g=ah(a,b||!1);break;default:return}V(P,f,g,h)},Wg=function(a){if(!Sg)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=ya(a);return Sg==If(c)},fh=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
P.gtmFormElementSubmitter||(P.gtmFormElementSubmitter=P.createElement("form"));return P.gtmFormElementSubmitter.submit.call?P.gtmFormElementSubmitter.submit:a.submit};var rg=new String("undefined"),rh=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===rg?b:a[d]);return c.join("")}};rh.prototype.toString=function(){return this.resolve("undefined")};rh.prototype.valueOf=rh.prototype.toString;var sh={},th=function(a,b){var c=ka++;sh[c]=[a,b];return c},uh=function(a){var b=a?0:1;return function(a){var d=sh[a];if(d&&L(d[b]))d[b]();sh[a]=void 0}};var vh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},wh=function(a,b){return a<b?-1:a>b?1:0};var xh;a:{var yh=za.navigator;if(yh){var zh=yh.userAgent;if(zh){xh=zh;break a}}xh=""}var X=function(a){return-1!=xh.indexOf(a)};var Ah=X("Opera"),Bh=X("Trident")||X("MSIE"),Ch=X("Edge"),Dh;if(Dh=X("Gecko"))Dh=!(-1!=xh.toLowerCase().indexOf("webkit")&&!X("Edge"));var Eh=Dh&&!(X("Trident")||X("MSIE"))&&!X("Edge"),Fh=-1!=xh.toLowerCase().indexOf("webkit")&&!X("Edge");Fh&&X("Mobile");X("Macintosh");X("Windows");X("Linux")||X("CrOS");var Gh=za.navigator||null;Gh&&(Gh.appVersion||"").indexOf("X11");X("Android");!X("iPhone")||X("iPod")||X("iPad");X("iPad");X("iPod");
var Hh=function(){var a=za.document;return a?a.documentMode:void 0},Ih;a:{var Jh="",Kh=function(){var a=xh;if(Eh)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Ch)return/Edge\/([\d\.]+)/.exec(a);if(Bh)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Fh)return/WebKit\/(\S+)/.exec(a);if(Ah)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Kh&&(Jh=Kh?Kh[1]:"");if(Bh){var Lh=Hh();if(null!=Lh&&Lh>parseFloat(Jh)){Ih=String(Lh);break a}}Ih=Jh}
var Mh=Ih,Nh={},Oh=function(a){var b;if(!(b=Nh[a])){for(var c=0,d=vh(String(Mh)).split("."),e=vh(String(a)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",k=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var n=m.exec(h)||["","",""],q=l.exec(k)||["","",""];if(0==n[0].length&&0==q[0].length)break;c=wh(0==n[1].length?0:parseInt(n[1],10),0==q[1].length?0:parseInt(q[1],10))||wh(0==n[2].length,0==q[2].length)||wh(n[2],q[2])}while(0==c)}b=Nh[a]=0<=c}return b},
Ph=za.document,Qh=Ph&&Bh?Hh()||("CSS1Compat"==Ph.compatMode?parseInt(Mh,10):5):void 0;var Rh;if(!(Rh=!Eh&&!Bh)){var Sh;if(Sh=Bh)Sh=9<=Number(Qh);Rh=Sh}Rh||Eh&&Oh("1.9.1");Bh&&Oh("9");var Th=function(a){Th[" "](a);return a};Th[" "]=function(){};var wa=function(a,b){var c="";Bh&&!Uh(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(Vh)a.srcdoc=d;else if(Wh){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else Xh(a,d)},Vh=Fh&&"srcdoc"in document.createElement("iframe"),Wh=Eh||Fh||Bh&&Oh(11),Xh=function(a,b){Bh&&Oh(7)&&!Oh(10)&&6>Yh()&&Zh(b)&&(b=$h(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};Bh&&!Uh(a)?ai(a,c):c()},Yh=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Uh=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{Th(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},bi=0,ai=function(a,b){var c="goog_rendering_callback"+bi++;window[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Zh=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},$h=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var di=function(a,b,c,d){return function(){try{if(0<b.length){var e=b.shift(),f=di(a,b,c,d);if("SCRIPT"==String(e.nodeName).toUpperCase()&&"text/gtmscript"==e.type){var g=P.createElement("script");g.async=!1;g.type="text/javascript";g.id=e.id;g.text=e.text||e.textContent||e.innerHTML||"";e.charset&&(g.charset=e.charset);var h=e.getAttribute("data-gtmsrc");h&&(g.src=h,pa(g,f));a.insertBefore(g,null);h||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(var k=[];e.firstChild;)k.push(e.removeChild(e.firstChild));
a.insertBefore(e,null);di(e,k,f,d)()}else a.insertBefore(e,null),f()}else c()}catch(m){r(d)}}};var fi=function(a,b,c){if(P.body){var d=
a[Hc];d instanceof rh&&(d=d.resolve(th(b,c)),b=Ve);if(a[Ke])try{wa(ha(),"<script>var google_tag_manager=parent.google_tag_manager;\x3c/script>"+d),r(b)}catch(e){r(c)}else a[Me]?ei(d,b,c):di(P.body,xa(d),b,c)()}else J.setTimeout(function(){fi(a,b,c)},200)},_html=fi;_html.a="html";_html.b=["customScripts"];
var ri=function(a,b,c,d){var e=b+": "+c+(d?" !important":""),f=document;if(f.createStyleSheet){var g=oi(f),h=g.rules.length;g.addRule(a,e);return function(){g.removeRule?g.removeRule(h):g.deleteRule(h);g.addRule("x","-",h)}}var k=pi(a+"{"+e+"}",f);qi(k,f);var m=k.parentNode;return function(){m.removeChild(k)}},si=null,oi=function(a){if(si)return si;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return si=c}0==a.styleSheets.length&&
a.createStyleSheet();return si=a.styleSheets[0]},pi=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},qi=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var zi={},Ai=void 0,Bi=function(a){var b=zi[a];b||(b={id:a,s:[],R:0,Ca:null,ua:void 0,ya:!1},zi[a]=b);Ai=b},Di=function(a,b,c,d){var e=Ai;if(!Sf||!e)return!1;var f={id:e.id+":"+e.s.length,Xa:b,O:[],Sa:c,D:a,ma:0,ka:d||null,Ga:0,P:!1};e.s.push(f);null===a?(f.P=!0,b(null)):Ci(e);return!0},Ei=function(a){var b=ri(a,"visibility","hidden",!0);return function(){L(b)&&b.apply();b=null}},Fi=function(a,b,c,d){var e=b;if(!ta){var f=Ei(a.v);ua.push(f);e=function(a,c){var d=b(a,c);f();return d}}return Di(a,e,
c,d)},Ci=function(a){if(!a.ya){for(var b=a.R;b<a.s.length;b++){var c=a.s[b],d=b==a.R;if(!c.P&&!Gi(d,c))break;c.P&&d&&a.R++}a.s.length>a.R?(a.Ca||(a.Ca=J.setTimeout(function(){a.Ca=null;Ci(a)},80)),ta||a.ua||(a.ua=function(){r(function(){Ci(a)})},V(P,"DOMContentLoaded",a.ua))):Hi(a)}},Hi=function(a){for(var b=0;b<a.s.length;b++){var c=a.s[b];if(c.D)for(var d=mf(c.D.v)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Ii(f,c.id),c.O.push(Ji(f,c.id)))}}},Gi=
function(a,b){var c=[];if(b.D){var d=Ki(b.D,b.id),e=null;b.ka&&(e=Ki(b.ka,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!ta&&(null===b.ka.m||b.Ga+c.length<b.ka.m)))break;c.push({element:g,xb:h})}}if(!ta&&b.Sa&&(!a||null==b.D.m||b.D.m!=b.ma+c.length))return!1;for(var k=0;k<c.length;k++){var m=c[k].element,l=c[k].xb,n;b.ma++;Ii(m,b.id);l&&(b.Ga++,n=b.id+"-t",Ii(l,n));var q=b.Xa(m,l);L(q)&&b.O.push(q);b.O.push(Ji(m,b.id));l&&n&&b.O.push(Ji(l,n))}if(b.D.m&&
b.D.m==b.ma||ta)b.P=!0;return!0},Ii=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Ji=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Ki=function(a,b){for(var c=mf(a.v)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.B&&!Li(f))break;d.push(f)}}return d},Li=function(a){if(ta)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Oi,Pi;var Zi=function(a){return function(){}},$i=function(a){return function(){}};var Aj=function(a){var b=J||za,c=b.onerror,d=!1;Fh&&!Oh("535.3")&&(d=!d);b.onerror=function(b,f,g,h,k){c&&c(b,f,g,h,k);a({message:b,fileName:f,qb:g,Nb:h,error:k});return d}};var Wj=22,Xj=[],Yj=[],Zj=[],ak=new bf,bk=[],Z=[],hh=[],ih=[],ck=function(){this.G=[]};ck.prototype.set=function(a,b){this.G.push([a,b]);return this};ck.prototype.resolve=function(a,b){for(var c={},d=0;d<this.G.length;d++){var e=dk(this.G[d][0],a,b),f=dk(this.G[d][1],a,b);c[e]=f}return c};var ek=function(a){this.index=a};ek.prototype.resolve=function(a,b){var c=Zj[this.index];if(c&&!b(c)){var d=c[Mc];if(a){if(a.get(d))return;a.set(d,!0)}c=dk(c,a,b);a&&a.set(d,!1);return cf(c)}};
var _M=function(a){return new ek(a)},fk=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=dk(Xj[a[f]],b,c);g===rg&&(e=!0);d.push(g)}return e?new rh(d):d.join("")}},_T=function(a){return new fk(arguments)},gk=function(a){function b(b){for(var d=1;d<a.length;d++)if(a[d]==b)return!0;return!1}this.resolve=
function(c,d){var e=dk(a[0],c,d);if(a[0]instanceof ek&&b(8)&&b(16)){if(e===rg)return e;var f="gtm"+ka++;ak.set(f,e);return'google_tag_manager["GTM-N7VWVN"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=Y[a[g]](e);return e}},_E=function(a,b){return new gk(arguments)},hk=function(a,b){this.u=a;this.ja=b},_R=function(a,b){return new hk(a,b)},ik=function(a,b){return dk(a,new bf,b)},dk=function(a,b,c){var d=a;if(a instanceof ek||a instanceof ck||a instanceof fk||a instanceof gk)return a.resolve(b,
c);if(!(a instanceof hk))if(U(a))for(var d=[],e=0;e<a.length;e++)d[e]=dk(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=dk(a[f],b,c))}return d},jk=function(a,b){var c=b[a],d=c;if(c instanceof ek||c instanceof gk||c instanceof fk||c instanceof hk)d=c;else if(U(c))for(var d=[],e=0;e<c.length;e++)d[e]=jk(c[e],b);else if("object"==typeof c){var d=new ck,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],jk(c[f],b))}return d},lk=function(a,b){for(var c=b?b.split(","):
[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=Xj[e[1]]);if(1==a)for(var f=kk(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=Yj[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=kk(e[g]);3==a&&(c[d]=Xj[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Xj[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},kk=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Wj;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=
e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},mk=function(a,b,c){a.push.apply(a,lk(b,c))};
var Ng=function(){},uk=function(a){},Qg=function(){},vk=function(a){},wk=function(a,b){},xk=function(a,b){},Og=function(a){};var yk=function(a){var b=this;this.g=a;this.complete=this.Oa=!1;this.ia=[];this.ca=[];this.M=function(){if(b.o&&b.o.event){var c=b.o.event,d=b.g;}b.complete||gf(b.ia);kf(b,1);if(La[a])for(var e=0;e<La[a].length;e++)La[a].shift().M()};this.L=function(){if(b.o&&b.o.event){var c=b.o.event,d=b.g;}b.complete||
gf(b.ca);kf(b,2);if(La[a])for(var e=0;e<La[a].length;e++)La[a].shift().L()};this.w=Ve},zk=function(a,b){a.ia.push(b)},Ak=function(a,b){a.ca.push(b)},Bk=function(a){this.H=[];this.Aa=[];this.Ia={};this.sa=[];this.S=0;this.Ma={};this.Qa={};this.Ba={};this.event=a};Bk.prototype.addListener=function(a){this.sa.push(a)};
var Ck=function(a,b,c,d,e,f){if(!c.complete){a.H[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=U(d)?d.slice():["or",d];e=U(e)?e.slice():[e];f=U(f)?f.slice():[f];a.Ia[b]=d;a.Ma[b]=0<e.length;a.Qa[b]=0<f.length;a.S++;var g=function(){0<a.S&&a.S--;0<a.S||gf(a.sa)};zk(c,g);Ak(c,g)}},Dk=function(a,b,c){a.H[b]&&(zk(a.H[b],function(){c(b,!0)}),Ak(a.H[b],function(){c(b,!1)}))},Ek=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof hk&&a[g].u===
d||a[g]===d){f=g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},Ik=function(a,b){var c=[],d=!1,e=function(b){var f,g,h=Z[b];if(a.event.c(h)){}else g=Fk(h,b,a);if(f=g){var k=Gk(b,!0);0<k.length&&e(k[0].u);c.push(f);var l=Gk(b,!1);0<l.length&&e(l[0].u)}else d=
!0};e(b);if(!d){for(var f=0;f<c.length;f++){var g=c[f],h=Gk(g.g,!0);if(0<h.length){var k=c[f-1],m=Hk(g);zk(k,m);0==h[0].ja&&Ak(k,m)}var l=Gk(g.g,!1);0<l.length&&(m=Hk(c[f+1]),zk(g,m),0==l[0].ja&&Ak(g,m))}a.Aa.push(c)}},Gk=function(a,b){var c=b?Xd:ne,d=Z[a],e=void 0===d[c]?[]:d[c];return U(e)?e:[e]},Hk=function(a){return function(){a.w()}},Kk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Gk(a,!0);0<b.length&&f(b[0].u);e.push(a);var c=Gk(a,!1);0<c.length&&f(c[0].u)};
f(d.g);b[d.g]=e}Jk(a,b);return b},Jk=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<Ye(b[e],d)){delete b[d];break}}};var Mk=function(a,b){return function(){a[Dc]=b.M;a[Ec]=b.L;var c=b.g,d=b.o&&b.o.Ba[c],e=Ka[c]&&Ka[c].state,f=d?void 0!==d:b.Oa||b.Ob,g=Ka[c]&&Ka[c].firingOption,h=g&&2==g,k=g&&1==g;if(!f&&void 0===e||!f&&!h||!h&&!k){kf(b,0);var m=b.o?b.o.event:void 0;a=Lk(a,m?m.c:Rf());if(m){var l=a;wk(m,c)}cf(a,b.M,b.L)}else h&&0==e||k&&0==d?La[c].push(b):h&&1==e||k&&1==d?b.M():b.L()}},Lk=function(a,b){a=ik(a,b);return a},Fk=function(a,b,c){var d=new yk(b);d.o=c;zk(d,Zi(a));Ak(d,$i(a));d.w=Mk(a,d);return d};var Rk,Sk;var al=!1;var bl=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=bk[b]&&ik(bk[b],c),e=d;if(d)if(d[Xa]&&U(d[R]))for(var f=d[R],e=!1,g=0;!e&&g<f.length;g++)d[R]=f[g],e=cf(d);else e=cf(d);a[b]=[e,d]}return a[b]}},tk=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.K(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.K(e[d],a.c)[0])return!1;return!0},cl=!1,Hg=function(a,b,c,d){switch(b){case "gtm.js":if(cl)return!1;cl=!0;break;case "gtm.sync":if(C("gtm.snippet")!=Ha)return!1}C("tagTypeBlacklist");
for(var e={id:a,name:b,Y:c||Ve,X:kk(),ha:kk(),K:bl(),c:Rf()},f=[],g=0;g<hh.length;g++)if(tk(e,hh[g])){f[g]=!0;for(var h=e,k=hh[g],m=k[1],l=0;l<m.length;l++)h.X[m[l]]=!0;for(var n=k[3],l=0;l<n.length;l++)h.ha[n[l]]=!0}else f[g]=!1;wk(e);var t=[];for(var v=0;v<Wj;v++)if(e.X[v]&&!e.ha[v])if(e.c(Z[v])){}else{t[v]=Z[v];}e.N=t;for(var x=new Bk(e),z=0;z<Wj;z++)if(e.X[z]&&!e.ha[z])if(e.c(Z[z])){}else{var E=e.N[z],F=Fk(E,z,x);Ck(x,z,F,E[Zb],E[Xd],E[ne]);if(E[Ma])break}x.addListener(e.Y);for(var D=[],y=
0;y<x.H.length;y++){var G=x.H[y];if(G){var w=x.Ia[y],B=x.Ma[y],H=x.Qa[y];if(0!=w.length||B||H){if(0<w.length)for(var Q=Ek(w,G.w),N=0;N<w.length;N++)w[N]instanceof hk&&w[N].u!=y&&Dk(x,w[N].u,Q);(B||H)&&Ik(x,y)}else D.push(y)}}for(y=0;y<D.length;y++)x.H[D[y]].w();for(y=0;y<x.Aa.length;y++){for(var sa=x.Aa[y],T=sa,fa=[],ca=0;ca<T.length;ca++){var nb=T[ca],lb=nb.g,Jb=Ka[lb],md=Jb.firingOption;0!=md&&(1==md&&void 0!==nb.o.Ba[lb]||2==md&&void 0!==Jb.state)&&fa.push(nb)}var nd=Kk(fa),qc=void 0;for(qc in nd)if(nd.hasOwnProperty(qc)){for(var pf=
void 0,fj=void 0,jd=nd[qc],pl=jd[0],mj=jd[jd.length-1],nj,Fa=0;Fa<T.length;Fa++){var kd=T[Fa];!pf&&kd.g==pl&&0<Fa&&(pf=T[Fa-1]);kd.g==mj&&Fa<T.length-1&&(fj=T[Fa+1]);if(-1<Ye(jd,kd.g))if(nj=T.splice(Fa,1)[0],kd.g==mj)break;else Fa--}if(nj){var oj=Number(qc),ja=pf,qf=fj;if(ja){var ql=ja.ia[0],rl=ja.ca[0],pj=ja;pj.ia=[];pj.ca=[];zk(ja,ql);Ak(ja,rl)}if(ja&&qf){var rf=Hk(qf);zk(ja,rf);var sf=Gk(ja.g,!1);0<sf.length&&sf[0].u!=oj&&0==sf[0].ja&&Ak(ja,rf);var tf=Gk(qf.g,!0);0<tf.length&&tf[0].u!=oj&&0==tf[0].ja&&
Ak(ja,rf)}}}0<sa.length&&sa[0].w()}0<x.S||gf(x.sa);d&&L(d)&&d({passingRules:f,resolvedTags:e.N});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var sj in e.N)if(e.N.hasOwnProperty(sj)){var tj=e.N[sj],uf;if(!(uf=void 0==tj[Mc])){var uj=tj[Mc];uf=!("function"!=typeof String.prototype.startsWith?0===uj.indexOf("_implicit"):uj.startsWith("_implicit"))}if(uf)return!0}return!1};var dl={macro:function(a){if(ak.contains(a))return ak.get(a)}};dl.dataLayer=Mf;dl.onHtmlSuccess=uh(!0);dl.onHtmlFailure=uh(!1);dl.ab=function(){var a=J.google_tag_manager;a||(a=J.google_tag_manager={});a["GTM-N7VWVN"]||(a["GTM-N7VWVN"]=dl);qa=a};(function(){var a=function(a){var c=I("google_tag_manager",{},!1),d=c[a];d||(d=c[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Tg=a("linkClickMap");Ug=a("formSubmitMap")})();
Xj.push.apply(Xj,function(){for(var a=[_eq,_e,'_event',_M(0),'gtm.js','1982030_2147479553',_html,100,true,'\x3cscript type\x3d\x22text/gtmscript\x22\x3e(function(a,e,f,g,b,c,d){a.GoogleAnalyticsObject\x3db;a[b]\x3da[b]||function(){(a[b].q\x3da[b].q||[]).push(arguments)};a[b].l\x3d1*new Date;c\x3de.createElement(f);d\x3de.getElementsByTagName(f)[0];c.async\x3d1;c.src\x3dg;d.parentNode.insertBefore(c,d)})(window,document,\x22script\x22,\x22https://www.google-analytics.com/analytics.js\x22,\x22ga\x22);ga(\x22create\x22,\x22UA-7078796-6\x22,\x22auto\x22);ga(\x22require\x22,\x22gabqplugin\x22);ga(\x22send\x22,\x22pageview\x22);\x3c/script\x3e\n\n\x3cscript async data-gtmsrc\x3d\x22https://tmgadata.appspot.com/js/gabq.js\x22 type\x3d\x22text/gtmscript\x22\x3e\x3c/script\x3e',3,_c,'GA ID','UA-7078796-6',_u,'Page URL','Page Hostname','host','Page Path','path',_f,'Referrer','Event'],b=[],c=0;c<a.length;c++)b[c]=jk(c,a);return b}());mk(Yj,0,"3:0,3:1,5:2,0:3,1:4,3:6,7:7,6:8,4:9,8:10,3:11,5:12,9:13,3:14,5:15,5:16,2:17,5:18,2:19,3:20,5:21,5:22");mk(Zj,1,"G,AwB,AAG,AAa,AAiB,AAAG,CAAI");mk(bk,1,"Z");mk(Z,1,"gP");mk(hh,2,"B:B::");mk(ih,4,"5:");for(var el=0;el<Z.length;el++){var fl=Z[el],gl=1;fl[sd]?gl=2:fl[Ge]&&(gl=0);Ka[el]={firingOption:gl,state:void 0};La[el]=[]}dl.ab();
(function(a){})("async");
(function(){var a=I("dataLayer",[],!1),b=I("google_tag_manager",{},!1),b=b["dataLayer"]=b["dataLayer"]||{};ua.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Ef.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Ig.push.apply(Ig,b);300<this.length;)this.shift();return Rg()};Ig.push.apply(Ig,a.slice(0));r(Rg)})();
if("interactive"==P.readyState&&!P.createEventObject||"complete"==P.readyState)wf();else{V(P,"DOMContentLoaded",wf);V(P,"readystatechange",wf);if(P.createEventObject&&P.documentElement.doScroll){var ol=!0;try{ol=!J.frameElement}catch(a){}ol&&yf()}V(J,"load",wf)}"complete"===P.readyState?Ff():V(J,"load",Ff);
(function(a){})("async");(function(){})();var _vs="res_ts:1465494894948000,srv_cl:125176656,ds:live,cv:20";
})()
